# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bf9f17bf3d2205acf91336c76349ae4a307b8d88aeffa9334199c203834c70a4f1815fc7a7a4110d0c20eb07a0faf81f4dfedf8de4c7e157f0ccdb33a2da802

test:
  secret_key_base: b8166099aaf0d35904141989d5a43f44d4464047a8492ab86b331f64c51e66d4a2fca2a765156193ebac7f1d760a66bef379ee20254599824d4088f84f96fe77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
